#!/usr/bin/env python3
# Writes the retrain patch with correct tab indentation
T = '\t'
lines = [
    "From: Opsero Electronic Design Inc.",
    "Subject: [PATCH] pcie-xilinx-dma-pl: Enable CommonClk and retrain link to Gen4",
    "",
    "After pci_host_probe() completes, the PCIe link may be stuck at 2.5GT/s",
    "(Gen1) because the PCI ASPM code skips CCC configuration when the root",
    "port reports \"ASPM not supported\". Without CCC, equalization phases 2 and",
    "3 fail, preventing link training beyond Gen1.",
    "",
    "This patch adds xilinx_pl_dma_pcie_retrain_link() which sets",
    "PCI_EXP_LNKCTL_CCC and triggers a link retrain after the host bridge is",
    "probed, allowing NVMe SSDs to negotiate Gen4 x4 (~7.8 GB/s).",
    "",
    "Only Gen4+ hardware (LNKCAP >= 16GT/s) triggers the retrain. On Versal",
    "QDMA in Gen3 mode, writing CCC+RL via ECAM stalls the AXI bus.",
    "",
    "--- a/drivers/pci/controller/pcie-xilinx-dma-pl.c",
    "+++ b/drivers/pci/controller/pcie-xilinx-dma-pl.c",
    "@@ -13,6 +13,7 @@",
    " #include <linux/msi.h>",
    " #include <linux/of_address.h>",
    " #include <linux/of_pci.h>",
    "+#include <linux/delay.h>",
    " ",
    " #include \"../pci.h\"",
    " #include \"pcie-xilinx-common.h\"",
    "@@ -819,6 +820,50 @@",
    f" {T}return 0;",
    " }",
    " ",
    "+static void xilinx_pl_dma_pcie_retrain_link(struct pci_host_bridge *bridge)",
    "+{",
    f"+{T}struct pci_dev *rp;",
    f"+{T}u32 lnkcap;",
    f"+{T}u16 lnksta, lnkctl;",
    "+",
    f"+{T}/* Find the root port device on bus 0 */",
    f"+{T}rp = list_first_entry_or_null(&bridge->bus->devices,",
    f"+{T}{T}{T}{T}      struct pci_dev, bus_list);",
    f"+{T}if (!rp || !pci_is_pcie(rp) ||",
    f"+{T}    pci_pcie_type(rp) != PCI_EXP_TYPE_ROOT_PORT)",
    f"+{T}{T}return;",
    "+",
    f"+{T}/*",
    f"+{T} * Only retrain if the hardware is Gen4 capable (16GT/s).",
    f"+{T} * On Versal QDMA in Gen3 mode, writing CCC+RL via ECAM stalls",
    f"+{T} * the AXI bus indefinitely.",
    f"+{T} */",
    f"+{T}pcie_capability_read_dword(rp, PCI_EXP_LNKCAP, &lnkcap);",
    f"+{T}if ((lnkcap & PCI_EXP_LNKCAP_SLS) < PCI_EXP_LNKCAP_SLS_16_0GB)",
    f"+{T}{T}return;",
    "+",
    f"+{T}/* Skip if already running faster than Gen1 */",
    f"+{T}pcie_capability_read_word(rp, PCI_EXP_LNKSTA, &lnksta);",
    f"+{T}if ((lnksta & PCI_EXP_LNKSTA_CLS) != PCI_EXP_LNKSTA_CLS_2_5GB)",
    f"+{T}{T}return;",
    "+",
    f"+{T}dev_info(&rp->dev,",
    f"+{T}{T} \"PCIe link at 2.5GT/s, enabling CommonClk and retraining\\n\");",
    "+",
    f"+{T}/* Enable Common Clock Configuration on root port */",
    f"+{T}pcie_capability_read_word(rp, PCI_EXP_LNKCTL, &lnkctl);",
    f"+{T}lnkctl |= PCI_EXP_LNKCTL_CCC;",
    f"+{T}pcie_capability_write_word(rp, PCI_EXP_LNKCTL, lnkctl);",
    "+",
    f"+{T}/* Trigger link retrain */",
    f"+{T}lnkctl |= PCI_EXP_LNKCTL_RL;",
    f"+{T}pcie_capability_write_word(rp, PCI_EXP_LNKCTL, lnkctl);",
    "+",
    f"+{T}/* Wait for retrain: fixed sleep avoids ECAM polling hang on Versal */",
    f"+{T}msleep(150);",
    f"+{T}dev_info(&rp->dev, \"PCIe link retrain: CCC+RL done\\n\");",
    "+}",
    "+",
    " static int xilinx_pl_dma_pcie_probe(struct platform_device *pdev)",
    " {",
    f" {T}struct device *dev = &pdev->dev;",
    "@@ -864,6 +920,8 @@",
    f" {T}if (err < 0)",
    f" {T}{T}goto err_host_bridge;",
    " ",
    f"+{T}xilinx_pl_dma_pcie_retrain_link(bridge);",
    "+",
    f" {T}return 0;",
    " ",
    " err_host_bridge:",
    "",
]

dest = '/home/zsolt/pesa101/FPGADEV/fpga-drive-aximm-pcie/PetaLinux/vck190_fmcp1/project-spec/meta-user/recipes-kernel/linux/linux-xlnx/0003-Add-CommonClk-and-link-retrain.patch'
with open(dest, 'w') as f:
    f.write('\n'.join(lines))
print("Written OK")
